"""Tunable parameters.

Collection of various tunable constants and functions.

"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


def WAREHOUSE_ID() -> str:
    """Get hard-coded SUMO ID of chosen warehouse.

    Returns:
        SUMO ID of warehouse.
    """
    return "239796134"


def PICKUP_CENTER_LIST() -> list[tuple[float, float]]:
    """Get hard-coded list of 2-D coordinates of centers of chosen pickup points.

    Returns:
        List of 2-D coordinates of pikcup points.
    """
    return [
        # List commented below is given hardcoded randomly by Prateek et. al
        # (1108.783925, 787.6503665714287),
        # (891.3527764504684, 588.4114269530795),
        # (908.783925, 987.6503665714287),
        # (1108.783925, 441.2402050576532),
        # (508.78392499999995, 787.6503665714287),
        # (1108.783925, 1134.0605280852042),
        # (1428.399167270663, 487.6503665714284),
        # (389.16868272933675, 1087.6503665714285),
        # (608.7839250000001, 1307.2656088420918),
        # (508.7839249999996, 94.83004354387799),
        # (1708.783925, 787.6503665714287),

        # List below is generated by map scanner code by Preetam
        (755.4149218394701, 637.9635952405185), #road = "-1174200828"
        (1191.4784417239305, 847.5790300041956), #road = "-158308044#0"
        (814.2789639425273, 1100.14651404885), #road = "-158308548#7"
        (1101.704316871461, 1199.8539443767297), #road = "-158308562#1"
        (558.0429017843524, 1019.5572052335372), #road = "-158320867#3"
        (594.6566651019727, 822.6165912609889), #road = "-158496670"
        (974.355694870897, 376.05268763060764), #road = "-164600317"
        (313.44196455423145, 326.94674811363365), #road = "-191363023#5"
        (274.3825036668454, 1173.5503883682009), #road = "154887808#0"
        (1356.3807326968497, 379.47974600546013), #road = "157973066#2"
        (1516.331130307601, 780.4600930963786), #road = "157973067#2"
        (1406.5073320341262, 1105.6309670235394), #road = "158004723"
        (1138.151126318533, 580.5383648990781), #road = "158028062"
        (266.9676504229391, 586.1509806838384), #road = "158184968#1"
        (628.6990461415111, 429.58155155985014), #road = "158184970#4"
        (315.77611747872777, 814.7737782996466), #road = "158199995#3"
        (654.0474596048682, 1198.4335799005808), #road = "158320865#1"
        (904.475790110294, 932.259786435413), #road = "158496689"

    ]


def VEHICLE_CAPACITY():
    """Generate capacities for vehicles.

    Returns:
        A (possibly random) capacity for a vehicle.
    """
    return 2  # random.randint(5, 15)


def DRONE_CAPACITY() -> int:
    """Generate capacities for drones.

    Returns:
        A (possibly random) capacity for a drone.
    """
    return 2  # random.randint(5, 15)


def DRONE_MAX_IDLE_STEPS() -> int:
    """Get hard-coded maximum number of allowed idle steps for drones.

    Returns:
        Maximum number of allowed idle steps for drones.
    """
    return 30


def DRONE_RANGE() -> float:
    """Generate flying range for drones.

    Returns:
        A (possibly random) flying range for a drone.
    """
    return 500.0


def DRONE_SPEED() -> float:
    """Generate flying speed for drones.

    Returns:
        A (possibly random) flying speed for a drone.
    """
    return 2.0


def PICKUP_CAPACITY() -> int:
    """Generate capacities for pickups.

    Returns:
        A (possibly random) capacity for a pickup.
    """
    return 2  # random.randint(5, 15)


def AVG_STEPS_PER_PACKAGE_REQUEST() -> int:
    """Generate capacities for pickups.

    Returns:
        A (possibly random) capacity for a pickup.
    """
    return 2  # random.randint(5, 15)
